// packages/example-v9-generic/src/stories/Basic.tsx
import React from "react";
import {stringify} from "@storybook-addon-deep-controls/common-internal";

export default function Basic(config: object) {
  return (
    <div>
      <h1>Config received by Component:</h1>
      <pre
        id='actual-config-json'
        style={{
          whiteSpace: "pre-wrap",
          wordWrap: "normal",
        }}
      >
        {stringify(config)}
      </pre>
    </div>
  );
}

// packages/example-v9-vue3-vite/src/stories/Basic.vue
<template>
  <div>
    <h1>Config received by Component:</h1>
    <pre id="actual-config-json" style="white-space: pre-wrap; word-wrap: normal">
      {{ configString }}
    </pre>
  </div>
</template>

<script setup lang="ts">
import {computed} from "vue";
import {stringify} from "@storybook-addon-deep-controls/common-internal";

const props = defineProps<{
  someObject: any;
}>();

// Computed properties
const configString = computed(() => stringify(props));
</script>
