// packages/example-v7-webpack/src/stories/Dev.tsx
import {stringify} from "@storybook-addon-deep-controls/common-internal";

export default function Dev(config: object) {
  return (
    <div>
      <h1>Config received by Component:</h1>
      <pre
        id='actual-config-json'
        style={{
          whiteSpace: "pre-wrap",
          wordWrap: "normal",
        }}
      >
        {stringify(config)}
      </pre>
    </div>
  );
}

// packages/example-v9-vue3-vite/src/stories/Dev.vue
<template>
  <div>
    <h1>Config received by Component:</h1>
    <pre id="actual-config-json" style="white-space: pre-wrap; word-wrap: normal">
      {{ configString }}
    </pre>
  </div>
</template>

<script setup lang="ts">
import {computed} from "vue";
import {stringify} from "@storybook-addon-deep-controls/common-internal";

const props = defineProps<{
  color?: any;
  emptyObj?: any;
  emptyArray?: any;
  someObject?: any;
  bool: any;
  string: any;
  number: any;
  jsx: any;
}>();

// Computed properties
const configString = computed((): string => stringify(props));
</script>
