// packages/example-v9-vue3-vite/src/stories/Basic.vue
<template>
  <div>
    <h1>Config received by Component:</h1>
    <pre id="actual-config-json" style="white-space: pre-wrap; word-wrap: normal">
      {{ configString }}
    </pre>
  </div>
</template>

<script setup lang="ts">
import {computed} from "vue";
import {stringify} from "@storybook-addon-deep-controls/common-internal";

const props = defineProps<{
  someObject: any;
}>();

// Computed properties
const configString = computed(() => stringify(props));
</script>

// packages/example-v8.5-vite-plain/stories/Basic.tsx
import React from "react";

export default function Basic(config: {
  obj: {
    bool: boolean;
    text: string;
  };
  bool: boolean;
  num: number;
  text: string;
}) {
  return (
    <div>
      <h1>Config received by Component:</h1>
      <pre
        id='actual-config-json'
        style={{
          whiteSpace: "pre-wrap",
          wordWrap: "normal",
        }}
      >
        {JSON.stringify(config, null, 2)}
      </pre>
    </div>
  );
}
