// packages/example-v9-vue3-vite/src/stories/WithTypedProps.vue
<template>
  <div>
    <h1>Config received by Component:</h1>
    <pre id="actual-config-json" style="white-space: pre-wrap; word-wrap: normal">
      {{ configString }}
    </pre>
  </div>
</template>

<script setup lang="ts">
import {computed} from "vue";
import {stringify} from "@storybook-addon-deep-controls/common-internal";

// NOTE: the docs addon will try to create argTypes for this component's props based on this types that this addon needs to handle
type Props = {
  someString?: string;
  someObject?: {
    anyString: string;
    enumString: string;
  };
  someArray?: string[];
};

const props = defineProps<Props>();

// Computed properties
const configString = computed(() => stringify(props));
</script>

// packages/example/src/stories/WithTypedProps.tsx
import React from "react";
import { stringify } from "storybook-addon-deep-controls/src/utils/general";

// NOTE: the docs addon will try to create argTypes for this component's props based on this types that this addon needs to handle
type Props = {
  someObject?: {
    anyString: string;
    enumString: string;
  };
};

export default function WithTypedProps(config: Props) {
  return (
    <div>
      <h1>Config received by Component:</h1>
      <pre
        id='actual-config-json'
        style={{
          whiteSpace: "pre-wrap",
          wordWrap: "normal",
        }}
      >
        {stringify(config)}
      </pre>
    </div>
  );
}
